bulletin_board/bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include

from bulletin_board import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('forum.urls')),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletin_board/forum/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.AnnouncementView.as_view(), name='home'),
    path('post/<int:announcement_id>/', views.DetailAnnouncementView.as_view(), name='post'),
    path('post/addpage/', views.AddAnnouncement.as_view(), name='add_page'),
    path('post/update/<int:pk>/', views.UpdateAnnouncement.as_view(), name='update_post'),
    path('post/delete/<int:pk>/', views.DeleteAnnouncement.as_view(), name='delete_post'),
    path('response/add/<int:pk>/', views.add_response, name='add_response'),
    path('response/list/<announcement_id>/', views.ListResponseFilter.as_view(), name='list_response'),
    path('response/accept/<int:pk>/', views.AcceptResponse.as_view(), name='accept_response'),
    path('response/delete/<int:pk>/', views.DeleteResponse.as_view(), name='delete_response'),
    path('news/', views.send_news_admin, name='send_news'),
    path('response<int:pk>/', views.DetailResponse.as_view(), name='response'),

]

bulletin_board/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

bulletin_board/templates/inc/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">Доска объявлений</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Главная</a></li>

            {% if request.user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'add_page' %}">Разместить объявление</a></li>
            {% endif %}

            {% if request.user.is_authenticated and user.is_superuser %}
            <li class="nav-item"><a class="nav-link" href="{% url 'send_news' %}">Новостная рассылка</a></li>
            {% endif %}

        </ul>

        <span class="navbar-text">

            {% if request.user.is_authenticated %}
            Welcome, <a href="{% url 'users:profile' %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">Выход</a>
            {% else %}
            <a href="{% url 'users:register' %}">Register</a> | <a href="{% url 'users:login' %}">Login</a>
            {% endif %}

        </span>
    </div>
</nav>

bulletin_board/templates/inc/pagination.html
{% if page_obj.has_other_pages %}
<nav aria-label="...">
    <ul class="pagination">

        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
        </li>
        {% endif %}

        {% for p in page_obj.paginator.page_range %}

        {% if page_obj.number == p %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ p }}">{{ p }} <span class="sr-only">(current)</span></a>
        </li>
        {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}